/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Oscar Alvarez
 */
public class PanelOpciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelOpciones
     */
    public PanelOpciones() {
        initComponents();

        this.buttonGroup1.add(this.AFD);
        this.buttonGroup1.add(this.AFND);
        this.buttonGroup1.add(this.AFNDL);
        this.buttonGroup1.add(this.bienvenidos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bienvenidos = new javax.swing.JRadioButton();
        AFD = new javax.swing.JRadioButton();
        AFND = new javax.swing.JRadioButton();
        AFNDL = new javax.swing.JRadioButton();
        INFO1 = new java.awt.Label();
        Aceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(189, 221, 255));
        setPreferredSize(new java.awt.Dimension(0, 312));

        bienvenidos.setText("Volver a la pantalla Inicial");

        AFD.setText("Utilizar Automata Finito Determinista");

        AFND.setText("Utilizar Automata Finito No Determinista");

        AFNDL.setText("Utilizar Automata Finito Determinista");

        INFO1.setName("INFO"); // NOI18N
        INFO1.setText("Este programa esta creado para observar, analizar");

        Aceptar.setText("Aceptar");
        Aceptar.setActionCommand("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INFO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AFNDL)
                    .addComponent(AFND)
                    .addComponent(AFD)
                    .addComponent(bienvenidos))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(INFO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bienvenidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFND)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFNDL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        if (this.bienvenidos.isSelected()) {
            System.out.println("Bienvenidos");
        } else if (this.AFD.isSelected()) {
            System.out.println("AFD");
        } else if (this.AFND.isSelected()) {
            System.out.println("AFND");
        } else if (this.AFNDL.isSelected()) {
            System.out.println("AFNDL");
        }
    }//GEN-LAST:event_AceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AFD;
    private javax.swing.JRadioButton AFND;
    private javax.swing.JRadioButton AFNDL;
    private javax.swing.JButton Aceptar;
    private java.awt.Label INFO1;
    private javax.swing.JRadioButton bienvenidos;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
